- client/login.html
- logIn.js
And changed language to english in html
> Updated login and resister account in js

- client/login.html
- css/logIn.css
Lade till forms för samtliga attribut som behövs i register account. Ingen css fixad än. Så endast för funktionalitet för tillfället.
> Added register forms

- allProductsPage.html
- api/receivers/userReceiver.php
- cartPage.html
- collectionPage.html
- css/common.css
- helperFunctions/fetchHelper.js
- index.html
- js/cart.js
- login.html
- myProfile.html
- productPage.html
Id, förnamn och efternamn finns tillgängliga på samtliga sidor om man vill använda dessa när en användare är inloggad.
Lade till så att förnamnet syns längst upp i hörnet vid inloggad användare (kan självklart ändras och flyttas om vi hittar ett bättre ställe)
> Display user

- allProductsPage.html
- api/receivers/cartReceiver.php
- cartPage.html
- collectionPage.html
- css/cartPage.css
- css/common.css
- css/productPage.css
- helperFunctions/fetchHelper.js
- index.html
- js/cart.js
- js/collectionPage.js
- js/logic.js
- js/productPage.js
- login.html
- myProfile.html
- productPage.html
För att inte riskera att det blir en för stor pullrequest i slutändan så skickar jag iväg en nu för att se så att det inte krockar med något. 
#17 
* Har lagt till så att totala kvantiten dyker upp i headern. Lade till en temporär design. Detta kan vi självklart snygga till sen.
* Om du försöker lägga till mer än vad som finns i unitsinstock så får du en alert. 
* Har påbörjat designen för carten. Är dock inte klar än.
> Add product to cart

- api/controllers/userController.php
- api/receivers/cartReceiver.php
- api/receivers/userReceiver.php
- css/cartPage.css
- helperFunctions/fetchHelper.js
- js/cart.js
Lade till en check out-knapp och hämtade hem fraktbolag
> Fixing get courrier

- api/receivers/userReceiver.php
- helperFunctions/fetchHelper.js
- helperFunctions/renderHelper.js
- js/admin.js
- js/allProductPage.js
- js/cart.js
- js/collectionPage.js
- js/logIn.js
- js/logic.js
- js/myProfilePage.js
- js/productPage.js
> Getting all values to create an order(CART)

- js/logIn.js
lade till så att man kommer till sign in när man registrerar ett konto
> sign in after registration

- api/classes/category.php
- api/classes/createInstanceFunctions.php
- api/classes/database.php
- api/classes/product.php
- api/controllers/categoryController.php
- api/controllers/courrierController.php
- api/controllers/orderController.php
- api/controllers/orderDetailsController.php
- api/controllers/productController.php
- api/controllers/userController.php
- api/receivers/cartReceiver.php
- api/receivers/orderReceiver.php
- api/receivers/productReceiver.php
- css/cartPage.css
- css/myProfile.css
- helperFunctions/fetchHelper.js
- helperFunctions/renderHelper.js
- js/allProductPage.js
- js/cart.js
- js/collectionPage.js
- js/myProfilePage.js
- js/productPage.js
- myProfile.html
#120  Bytt namn på categoryId och productId till Id i projektet.
#12 Man kan sätta antal på en produkt när man är admin. Kvar - Lägg till addera och subtrahera
* Har fixat en layout på adminsidan som vi kan jobba i
> Update qty, adminLayout and change Id's

- css/common.css
- css/myProfile.css
- js/myProfilePage.js
- myProfile.html
.orderButton {
width: 15px !important;
padding: 2px 15px !important;
font-size: 6px !important;
}
.cell {
font-size: 7px;
}
.orderHeader {
font-size: 8px;
}
}
> orders on adminpage

- api/classes/newsletter.php
- css/common.css
- css/productPage.css
- js/myProfilePage.js
- js/productPage.js
- productPage.html
not anything done with either nav, footer or about section.
> made productPage responsive

- api/classes/database.php
- api/classes/order.php
- api/classes/product.php
- api/controllers/orderController.php
- api/controllers/productController.php
- css/cartPage.css
När jag lade till attributen i klasserna order och product som vi vill använda till order-getbyid så hamnade dessa även i instansen till order och product. Detta löstes dock sen med en unset på de tillagda attributen. Får checka med Victor om det finns ett mer bättre sätt praxis, men det funkar nu iaf att skapa order samt uppdatera produkt när dessa attribut är tillagda nu iaf :)
> unset attributes

- allProductsPage.html
- cartPage.html
- collectionPage.html
- css/collectionPage.css
- css/common.css
- css/startPage.css
- index.html
- login.html
- myProfile.html
- productPage.html
> Responsive-startpage

- api/classes/database.php
- api/controllers/orderController.php
- api/controllers/productController.php
- api/controllers/userController.php
- api/receivers/cartReceiver.php
- api/receivers/orderReceiver.php
- js/cart.js
- js/myProfilePage.js
> Error register account

- api/classes/createInstanceFunctions.php
- api/classes/database.php
- api/classes/productInCategory.php
- api/controllers/categoryController.php
- api/controllers/courrierController.php
- api/controllers/newsLetterController.php
- api/controllers/orderController.php
- api/controllers/orderDetailsController.php
- api/controllers/orderStatusController.php
- api/controllers/productController.php
- api/controllers/productInCategoryController.php
- api/controllers/subscriptionNewsController.php
- api/controllers/userController.php
- api/receivers/categoryReceiver.php
- api/receivers/productInCategoryReceiver.php
- api/receivers/productReceiver.php
- css/myProfile.css
- helperFunctions/fetchHelper.js
- js/cart.js
- js/myProfilePage.js
- myProfile.html
#28 Klar! 
#204 Blev en liten fix som hoppade in här också.
> Modify category

- api/controllers/orderDetailsController.php
- api/controllers/productController.php
- api/controllers/productInCategoryController.php
- api/receivers/cartReceiver.php
- api/receivers/orderReceiver.php
- css/myProfile.css
- js/cart.js
- js/myProfilePage.js
> Cart quantity

- helperFunctions/renderHelper.js
- js/allProductPage.js
- js/cart.js
- js/collectionPage.js
- js/logIn.js
- js/logic.js
- js/myProfilePage.js
- js/productPage.js
> Moved burger to renderhelper

- js/logIn.js
- js/myProfilePage.js
> rearranged my order in admin

- api/controllers/orderController.php
- api/controllers/orderDetailsController.php
- api/controllers/productController.php
- api/controllers/subscriptionNewsController.php
- api/controllers/userController.php
- api/receivers/userReceiver.php
- css/myProfile.css
- js/allProductPage.js
- js/myProfilePage.js
- myProfile.html
And some responsivity on admin page
> Checking validation

- api/receivers/productReceiver.php
- js/myProfilePage.js
Error-meddelanden kommer ut till klienten.
> Echo errors - Product and category

- css/myProfile.css
- css/productPage.css
- css/startPage.css
- js/logic.js
- Worked with startpage
- Collection section
- Read more button - About 
- Removed some CSS
> Startpage read more

- css/startPage.css
- index.html
> startpage-css
